# Generated by Django 2.0.5 on 2018-05-26 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icao', models.CharField(blank=True, max_length=3, null=True)),
                ('iata', models.CharField(blank=True, max_length=2, null=True)),
                ('name', models.CharField(max_length=255)),
                ('name_traditional', models.CharField(max_length=255)),
                ('name_simplified', models.CharField(max_length=255)),
                ('phone_enquiry', models.CharField(blank=True, max_length=32, null=True)),
                ('phone_reservation', models.CharField(blank=True, max_length=32, null=True)),
                ('url', models.URLField(blank=True, max_length=255, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'airline',
            },
        ),
        migrations.CreateModel(
            name='AirlineAisle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Airline')),
            ],
            options={
                'db_table': 'airline_aisle',
            },
        ),
        migrations.CreateModel(
            name='AirlineLounge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Airline')),
            ],
            options={
                'db_table': 'airline_lounge',
            },
        ),
        migrations.CreateModel(
            name='AirlineTransferDesk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Airline')),
            ],
            options={
                'db_table': 'airline_transfer_desk',
            },
        ),
        migrations.CreateModel(
            name='Aisle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1)),
                ('airlines', models.ManyToManyField(through='core.AirlineAisle', to='core.Airline')),
            ],
            options={
                'db_table': 'aisle',
            },
        ),
        migrations.CreateModel(
            name='GroundHandling',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(db_index=True, max_length=64)),
                ('slug', models.CharField(db_index=True, max_length=64)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'ground_handling',
            },
        ),
        migrations.CreateModel(
            name='Lounge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1)),
                ('airlines', models.ManyToManyField(through='core.AirlineLounge', to='core.Airline')),
            ],
            options={
                'db_table': 'lounge',
            },
        ),
        migrations.CreateModel(
            name='TransferDesk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1)),
                ('airlines', models.ManyToManyField(through='core.AirlineTransferDesk', to='core.Airline')),
            ],
            options={
                'db_table': 'transfer_desk',
            },
        ),
        migrations.AddField(
            model_name='airlinetransferdesk',
            name='transfer_desk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.TransferDesk'),
        ),
        migrations.AddField(
            model_name='airlinelounge',
            name='lounge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Lounge'),
        ),
        migrations.AddField(
            model_name='airlineaisle',
            name='aisle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Aisle'),
        ),
        migrations.AddField(
            model_name='airline',
            name='aisles',
            field=models.ManyToManyField(through='core.AirlineAisle', to='core.Aisle'),
        ),
        migrations.AddField(
            model_name='airline',
            name='lounges',
            field=models.ManyToManyField(through='core.AirlineLounge', to='core.Lounge'),
        ),
        migrations.AddField(
            model_name='airline',
            name='transfer_desks',
            field=models.ManyToManyField(through='core.AirlineTransferDesk', to='core.TransferDesk'),
        ),
    ]
