# Generated by Django 2.0.5 on 2018-05-26 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180526_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='airline',
            name='terminal',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.Terminal'),
            preserve_default=False,
        ),
    ]
