# Generated by Django 2.0.5 on 2018-05-26 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_airline_terminal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airline',
            name='terminal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Terminal'),
        ),
    ]
