# Generated by Django 2.0.5 on 2018-05-26 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20180526_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='lounge',
            name='external_id',
            field=models.CharField(db_index=True, default='', max_length=64),
            preserve_default=False,
        ),
    ]
