# Generated by Django 2.0.5 on 2018-05-26 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_lounge_external_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lounge',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
