# Generated by Django 2.0.5 on 2018-05-26 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_airline_ground_handling'),
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icoa', models.CharField(blank=True, db_index=True, max_length=4, null=True, unique=True)),
                ('iata', models.CharField(db_index=True, max_length=3, unique=True)),
                ('country', models.CharField(db_index=True, max_length=2)),
                ('name', models.CharField(max_length=255)),
                ('name_traditional', models.CharField(max_length=255)),
                ('name_simplified', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'airport',
            },
        ),
        migrations.AlterField(
            model_name='airline',
            name='iata',
            field=models.CharField(db_index=True, max_length=2, unique=True),
        ),
        migrations.AlterField(
            model_name='airline',
            name='icao',
            field=models.CharField(db_index=True, max_length=3, unique=True),
        ),
    ]
