# Generated by Django 2.0.5 on 2018-05-26 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20180526_1703'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlightNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airline_letters', models.CharField(max_length=2)),
                ('number', models.CharField(max_length=5)),
                ('number_ordering', models.IntegerField()),
                ('airline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Airline')),
            ],
            options={
                'db_table': 'flight_number',
            },
        ),
        migrations.RenameField(
            model_name='airport',
            old_name='icoa',
            new_name='icao',
        ),
    ]
