# Generated by Django 2.0.5 on 2018-05-26 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20180527_0229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airport',
            name='country',
            field=models.CharField(blank=True, db_index=True, max_length=2, null=True),
        ),
    ]
