# Generated by Django 2.0.5 on 2018-05-26 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20180527_0231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airline',
            name='icao',
            field=models.CharField(blank=True, db_index=True, max_length=3, null=True, unique=True),
        ),
    ]
