# Generated by Django 2.0.5 on 2018-05-26 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20180527_0235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airline',
            name='iata',
            field=models.CharField(blank=True, db_index=True, max_length=2, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='airline',
            name='icao',
            field=models.CharField(db_index=True, default='', max_length=3, unique=True),
            preserve_default=False,
        ),
    ]
