# Generated by Django 2.0.5 on 2018-05-26 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20180527_0237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airline',
            name='name_simplified',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='airline',
            name='name_traditional',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
