# Generated by Django 2.0.5 on 2018-05-26 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20180527_0250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airline',
            name='iata',
            field=models.CharField(blank=True, db_index=True, max_length=2, null=True),
        ),
    ]
