# Generated by Django 2.0.5 on 2018-05-26 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20180527_0258'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArrivalStand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
            ],
            options={
                'db_table': 'arrival_stand',
            },
        ),
        migrations.CreateModel(
            name='Departure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'departure',
            },
        ),
        migrations.CreateModel(
            name='DepartureAisle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule', models.DateTimeField()),
                ('aisle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Aisle')),
                ('departure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Departure')),
            ],
            options={
                'db_table': 'departure_aisle',
            },
        ),
        migrations.CreateModel(
            name='DepartureGate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
            ],
            options={
                'db_table': 'departure_gate',
            },
        ),
        migrations.AddField(
            model_name='departureaisle',
            name='gate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.DepartureGate'),
        ),
        migrations.AddField(
            model_name='departure',
            name='aisles',
            field=models.ManyToManyField(through='core.DepartureAisle', to='core.Aisle'),
        ),
        migrations.AddField(
            model_name='departure',
            name='flight_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departures', to='core.FlightNumber'),
        ),
        migrations.AddField(
            model_name='departure',
            name='terminal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='departures', to='core.Terminal'),
        ),
        migrations.AddField(
            model_name='aisle',
            name='departures',
            field=models.ManyToManyField(through='core.DepartureAisle', to='core.Departure'),
        ),
        migrations.AlterUniqueTogether(
            name='departureaisle',
            unique_together={('departure', 'aisle')},
        ),
    ]
