# Generated by Django 2.0.5 on 2018-05-26 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20180527_0332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departureaisle',
            name='gate',
        ),
        migrations.RemoveField(
            model_name='departureaisle',
            name='schedule',
        ),
        migrations.AddField(
            model_name='departure',
            name='gate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.DepartureGate'),
        ),
        migrations.AddField(
            model_name='departure',
            name='schedule',
            field=models.DateTimeField(default='2018-01-01'),
            preserve_default=False,
        ),
    ]
