# Generated by Django 2.0.5 on 2018-05-26 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20180527_0334'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartureDestination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'departure_destination',
            },
        ),
        migrations.CreateModel(
            name='DepartureFlightNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'departure_flight_number',
            },
        ),
        migrations.RemoveField(
            model_name='departure',
            name='flight_number',
        ),
        migrations.AddField(
            model_name='departureflightnumber',
            name='departure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Departure'),
        ),
        migrations.AddField(
            model_name='departureflightnumber',
            name='flight_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.FlightNumber'),
        ),
        migrations.AddField(
            model_name='departuredestination',
            name='departure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Departure'),
        ),
        migrations.AddField(
            model_name='departuredestination',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Airport'),
        ),
        migrations.AddField(
            model_name='airport',
            name='departures',
            field=models.ManyToManyField(through='core.DepartureDestination', to='core.Departure'),
        ),
        migrations.AddField(
            model_name='departure',
            name='destinations',
            field=models.ManyToManyField(through='core.DepartureDestination', to='core.Airport'),
        ),
        migrations.AddField(
            model_name='departure',
            name='flight_numbers',
            field=models.ManyToManyField(through='core.DepartureFlightNumber', to='core.FlightNumber'),
        ),
        migrations.AddField(
            model_name='flightnumber',
            name='departures',
            field=models.ManyToManyField(through='core.DepartureFlightNumber', to='core.Departure'),
        ),
        migrations.AlterUniqueTogether(
            name='departureflightnumber',
            unique_together={('departure', 'flight_number')},
        ),
        migrations.AlterUniqueTogether(
            name='departuredestination',
            unique_together={('departure', 'destination')},
        ),
    ]
