# Generated by Django 2.0.5 on 2018-05-26 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20180527_0351'),
    ]

    operations = [
        migrations.CreateModel(
            name='Arrival',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule', models.DateTimeField()),
                ('baggage_reclaim', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='arrivals', to='core.BaggageReclaim')),
            ],
            options={
                'db_table': 'arrival',
            },
        ),
        migrations.CreateModel(
            name='ArrivalFlightNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=1)),
                ('arrival', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Arrival')),
                ('flight_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.FlightNumber')),
            ],
            options={
                'db_table': 'arrival_flight_number',
            },
        ),
        migrations.CreateModel(
            name='ArrivalOrigin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrival', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Arrival')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Airport')),
            ],
            options={
                'db_table': 'arrival_origin',
            },
        ),
        migrations.CreateModel(
            name='ArrivalStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_code', models.CharField(max_length=2)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('arrival', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='core.Arrival')),
            ],
            options={
                'db_table': 'arrival_status',
            },
        ),
        migrations.AddField(
            model_name='arrival',
            name='flight_numbers',
            field=models.ManyToManyField(through='core.ArrivalFlightNumber', to='core.FlightNumber'),
        ),
        migrations.AddField(
            model_name='arrival',
            name='hall',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Hall'),
        ),
        migrations.AddField(
            model_name='arrival',
            name='origins',
            field=models.ManyToManyField(through='core.ArrivalOrigin', to='core.Airport'),
        ),
        migrations.AddField(
            model_name='arrival',
            name='stand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='arrivals', to='core.Stand'),
        ),
        migrations.AddField(
            model_name='airport',
            name='arrivals',
            field=models.ManyToManyField(through='core.ArrivalOrigin', to='core.Arrival'),
        ),
        migrations.AddField(
            model_name='flightnumber',
            name='arrivals',
            field=models.ManyToManyField(through='core.ArrivalFlightNumber', to='core.Arrival'),
        ),
        migrations.AlterUniqueTogether(
            name='arrivalorigin',
            unique_together={('arrival', 'origin')},
        ),
        migrations.AlterUniqueTogether(
            name='arrivalflightnumber',
            unique_together={('arrival', 'flight_number')},
        ),
    ]
