# Generated by Django 2.0.5 on 2018-05-26 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20180527_0357'),
    ]

    operations = [
        migrations.AddField(
            model_name='departure',
            name='latest_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='latest', to='core.DepartureStatus'),
        ),
    ]
