# Generated by Django 2.0.5 on 2018-05-26 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_arrival_latest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airport',
            name='name_simplified',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='airport',
            name='name_traditional',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
