# Generated by Django 2.0.5 on 2018-05-26 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_auto_20180527_0509'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='terminal',
            name='slug',
        ),
        migrations.AddField(
            model_name='terminal',
            name='name',
            field=models.CharField(db_index=True, default='', max_length=16),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aisle',
            name='name',
            field=models.CharField(db_index=True, max_length=16),
        ),
        migrations.AlterField(
            model_name='transferdesk',
            name='name',
            field=models.CharField(db_index=True, max_length=16),
        ),
    ]
