# Generated by Django 2.0.5 on 2018-05-26 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_auto_20180527_0556'),
    ]

    operations = [
        migrations.AddField(
            model_name='arrival',
            name='actual',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='departure',
            name='actual',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
