# Generated by Django 2.0.5 on 2018-05-29 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_auto_20180527_0655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arrival',
            name='schedule',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='departure',
            name='schedule',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='flightnumber',
            name='airline_letters',
            field=models.CharField(db_index=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='flightnumber',
            name='number',
            field=models.CharField(db_index=True, max_length=5),
        ),
    ]
