# Generated by Django 2.0.5 on 2018-05-28 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FrLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight', models.CharField(blank=True, db_index=True, max_length=16, null=True)),
                ('registration', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('model', models.CharField(blank=True, db_index=True, max_length=16, null=True)),
                ('callsign', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('origin', models.CharField(blank=True, db_index=True, max_length=3, null=True)),
                ('destination', models.CharField(blank=True, db_index=True, max_length=3, null=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('bearing', models.IntegerField(blank=True, null=True)),
                ('altitude', models.IntegerField(blank=True, null=True)),
                ('vertical_speed', models.IntegerField(blank=True, null=True)),
                ('speed', models.IntegerField(blank=True, null=True)),
                ('radar', models.CharField(blank=True, max_length=64, null=True)),
                ('mode_s_code', models.CharField(blank=True, max_length=255, null=True)),
                ('squawk', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('unknown_boolean', models.BooleanField()),
                ('unknown_boolean_2', models.BooleanField()),
                ('hash', models.CharField(db_index=True, max_length=32)),
            ],
            options={
                'db_table': 'fr_log',
            },
        ),
    ]
