# Generated by Django 2.0.5 on 2018-05-28 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fr', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='frlog',
            index=models.Index(fields=['registration', 'timestamp'], name='fr_log_registr_0be1a0_idx'),
        ),
    ]
